sudo: required
services:
  - docker
before_install:
  - docker build -t cengsili/complex-test -f ./client/Dockerfile.dev ./client
script:
  - docker run cengsili/complex-test npm test -- --coverage
after_success:
  - docker build -t cengsili/complex-client ./client
  - docker build -t cengsili/complex-nginx ./nginx
  - docker build -t cengsili/complex-server ./server
  - docker build -t cengsili/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cengsili/complex-client
  - docker push cengsili/complex-nginx
  - docker push cengsili/complex-server
  - docker push cengsili/complex-worker