sudo: required
services:
  - docker
before_install:
  - docker build -t complex-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev
script:
  - docker run complex-test npm test -- --coverage
after-success: 
  - docker build -t complex-client ./client
  - docker build -t complex-nginx ./nginx
  - docker build -t complex-server ./server
  - docker build -t complex-worker ./worker
  #Log in
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin