sudo: required
services:
  - docker
before_install:
  - docker build -t complex-test -f ./client/Dockerfile.dev ./client
script:
  - docker run complex-test npm test -- --coverage
after_success:
  - docker build -t complex-client ./client
  - docker build -t complex-nginx ./nginx
  - docker build -t complex-server ./server
  - docker build -t complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push complex-client
  - docker push complex-nginx
  - docker push complex-server
  - docker push complex-worker